// <auto-generated />
namespace e_Book.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDownloadLinkToBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDownloadLinkToBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "202412102012019_AddDownloadLinkToBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
